### ISSUE TITLE
Please remove binary cfourcc from git repository

### ISSUE THREAD

**Issue by jaalto** [mypapit/cfourcc#2]
Hi,

It would be helpful if the binary could be removed from the Git source tree. If this is not possible e.g. if you want to keep it "precompiled for easy personal use", please consider moving it to a separate branch like "binay/".

Removing the binary would help a lot. In package development, the upstream sources are imported in full for each release. If he sources include the binary, this is what happens in the packaging workflow:

  1. clone git
  2a. Import FULL to locally (Packaging work)
  2b. Lay out the packging infrastructure over the sources.
  3. compile  (...this will replace binary on ARCH)
  4. diff?   ...Erm, problem. Binary has been replaced by the compile.  The *original* sources have changed although no code has been touched.
  5. commit?
  Nope, would't like to commit the binary

Thanks,
Jari

**Comment by mypapit** [comment]
already removed the binary from master branch and release 0.1.3a. Thanks for the issue
